# Организация обучения {.unnumbered}

## Цели и задачи

Цель курса – познакомить слушателя с источниками данных, рабочими инструментами в иммуноинформатике и принципами их работы. В курсе рассматриваются экспериментальные методы, применяемые в фундаментальной и клинической иммунологии вместе с методами анализа результатов экспериментов. Разбираются технические аспекты применения вычислительных методов. Особое внимание уделено вопросам компьютерного конструирования вакцин.

## Ожидаемые результаты обучения

После изучения курса слушатель получит представление о применении методов биоинформатики в иммунологии и используемых и информационных ресурсах. Слушатель научится применять продвинутые технические инструменты для решения как иммуноинформатических, так и общих биоинформатических задач.

## Приобретаемые знания

-   Знание медицинской классификации генетических вариантов, алгоритма вынесения заключения по результатам высокопроизводительного секвенирования.

-   Знание об алгоритмах, используемых в картировании прочтений локуса HLA.

-   Понимание принципов работы программ-предсказателей

-   Понимание особенностей открытых на момент преподавания курса иммунологических данных

-   Знание о принципах и этапах компьютерного конструирования вакцин и иммунологических препаратов

-   Понимание принципов анализа результатов single-cell RNA секвенирования.

-   Понимание принципов моделирования трехмерных структур.

## Приобретаемые навыки

-   Навыки работы с общедоступными биоинформатическими базами данных

-   Навыки работы с интерфейсом командной строки, работы в операционной системе Linux

-   Навыки написания программ на языке программирования Python, R для решения иммуноинформатических задач

-   Умение применять иммуноинформатические онлайн-инструменты, интерпретировать их результаты 

-   Способность решать иммуноинформатические задачи как прикладного (медицинского), так и фундаментального характера.

## Система оценивания

Дисциплина предполагает получение «зачета». Для «зачета» необходимо достичь порогового показателя в 60% по каждому виду деятельности:

|                                   |                  |                               |                                 |
|-----------------------------------|------------------|-------------------------------|---------------------------------|
| **Виды деятельности**             | **Итого, баллы** | **Пороговое значение, баллы** | **Комментарии**                 |
| Работа на очных занятиях          | 70               | 42                            | 7 занятий по 10 баллов          |
| Индивидуальная домашняя работа    | 40               | 24                            | 4 домашних задания по 10 баллов |
| Проект по конструированию вакцины | 20               | 12                            |                                 |
| Итоговое устное собеседование     | 30               | 18                            |                                 |
| **Итого**                         | **160**          | **96**                        |                                 |

## Учебные материалы

### Основная литература

1.  Мерфи, К. Иммунобиология по Джанвэю / К. Мерфи, К. Уивер; пер. с англ.; под ред. Г.А. Игнатьевой, О.А. Свитич, И.Н. Дьякова. - М.: Логосфера, 2020. - 1184 с. : ил. : 21,3 см. ISBN 978-5-98657-070-9

2.  Руководство по интерпретации данных последовательности ДНК человека, полученных методами массового параллельного секвенирования (MPS) (редакция 2018, версия 2) <https://ngs.med-gen.ru/mgngs19/%D0%A0%D1%83%D0%BA%D0%BE%D0%B2%D0%BE%D0%B4%D1%81%D1%82%D0%B2%D0%BE%20NGS%202019%20%D0%B2%D0%B5%D1%80.2.pdf>

3.  Namrata Tomar. Immunoinformatics. [Springer Protocols](https://link.springer.com/search?facet-content-type=%22Book%22&package=12345&facet-start-year=2020&facet-end-year=2020) 3 ed., 2020 DOI: <https://doi.org/10.1007/978-1-0716-0389-5>

4.  [Pedro A. Reche](https://link.springer.com/book/10.1007/978-1-0716-3239-0#author-1-0). Computational Vaccine Design 1 ed., 2023 DOI: <https://doi.org/10.1007/978-1-0716-3239-0> 

5.  Курс «Анализ транскриптомных данных», Сергей Исаев. <https://github.com/serjisa/transcriptomics.msu>
